{{- if not .Values.api.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spinscout.apiSecretName" . }}
  labels:
    {{- include "spinscout.labels" . | nindent 4 }}
type: Opaque
stringData:
  STRAVA_CLIENT_ID: {{ .Values.api.secrets.stravaClientId | quote }}
  STRAVA_CLIENT_SECRET: {{ .Values.api.secrets.stravaClientSecret | quote }}
  GRAPHHOPPER_API_KEY: {{ .Values.api.secrets.graphhopperApiKey | quote }}
  APP_SECRET: {{ .Values.api.secrets.appSecret | quote }}
{{- end }}
